### ISSUE TITLE
Cannot Toggle Airplay

### ISSUE THREAD

**Issue by aiden21c** [mvdwetering/yamaha_ynca#133] opened 2023-02-13 12:59 UTC
Upon discovery and initial integration, I believe everything worked however after playing with setting up a HA scene, I am no longer able to toggle into Airplay. The device simply stays in its previous source mode. When I toggle Airplay manually on the device in the Yamaha app, the Source in HA is blank so it seems HA and the receiver are not communicating the Airplay source correctly.

I have tried restarting HA as well as the receiver. I have also tried disabling the previously created scene and this did not seem to work. I'm very much a noob with HA so I'm not too sure how else to trouble shoot this.

**Comment by mvdwetering** [comment] 2023-02-13 18:47
Looks like there is an error in the integration in the mapping from the receiver commands to Home Assistant.

Can you do the following steps:
* Select a different source than Airplay (e.g. HDMI1)
* Select Airplay in Home Assistant
* Select another source again (e.g. HDMI1)
* Use another way to select Airplay, not sure how it works, I guess through Yamaha App or on the receiver itself
* Then in Home Assistant navigate to the integration page under Settings > Devices & services and open the "⋮" menu on the YNCA integration card and then select the option "Download diagnostics". A diagnostics file will be downloaded. Please post the file here (attach the file, do not copy-paste content as it is quite big) so I can have a look.

The diagnostics file has the most recent commands in it so I can see the messages from the receivers and if there were any errors.

**Comment by aiden21c** [comment] 2023-02-13 21:00
[config_entry-yamaha_ynca-92c87f729c25299388a189a17d0195cc.zip](https://github.com/mvdwetering/yamaha_ynca/files/10726257/config_entry-yamaha_ynca-92c87f729c25299388a189a17d0195cc.zip)

Please let me know if there is any further testing you might need.

**Comment by mvdwetering** [comment] 2023-02-14 20:28
There was a typo I had "Airplay" instead of "AirPlay" (note the capital P) I have that fixed as far as I can tell.
I noticed in your diagnotics that the Airplay source also seems to support Album, Artist, Song and playback info (play/pause status)

Could you try the latest dev build?
When using HACS open the HACS integration page, select Yamah YNCA integration, then top right select the triple dot menu and select "Redownload". Then make sure "Show beta" is selected and then in the dropdown with the versions select "dev".
Then update the integration.

After this could you try select the Airplay source and play a few songs and see if there is a play/pause/stop button (not sure which ones are supported) and that the song, artist and/or album info shows in the mediaplayer card. After trying this please send a new diagnostics file, so I can double check if it is all working as intended.

**Comment by aiden21c** [comment] 2023-02-16 07:31
I've done some testing and that seems to have done the trick. All the play, pause, forward and back buttons seem to work as expected. The only issue I did have was that when I start an Airplay to the device, there is about a 20-30 second delay before the receiver recognises the connection and begins to play the audio. This delay also occurs when resuming paused playback in exactly the same way. Also the "pause" button does not turn into a "play" button when clicked, the http page needs to be refreshed for the web page to recognize the music is paused.

[config_entry-yamaha_ynca-92c87f729c25299388a189a17d0195cc.zip](https://github.com/mvdwetering/yamaha_ynca/files/10753243/config_entry-yamaha_ynca-92c87f729c25299388a189a17d0195cc.zip)

**Comment by aiden21c** [comment] 2023-02-16 13:34
I've found a second issue whereby Airplay suddenly stopped playing back audio. The sequence of events were as follows:
- Connect airplay and begin playback
- 30 second delay while song plays before receiver picks up the signal
- 30 seconds of actual music playback
- Music continues playing however no sound is output by the receiver. Both the receiver and the device act as if the transmission is still occurring and no issue seems to be reported.

I then shut down the receiver and turned it back on and this has now put the receiver in an uncastable state. If I try to begin airplay to it, the phone says "this device is in use by someone else" and it refuses to connect to my phone. I'll attach the diagnostics in the morning.

**Comment by mvdwetering** [comment] 2023-02-16 20:32
> The only issue I did have was that when I start an Airplay to the device, there is about a 20-30 second delay before the receiver recognises the connection and begins to play the audio

> I then shut down the receiver and turned it back on and this has now put the receiver in an uncastable state. If I try to begin airplay to it, the phone says "this device is in use by someone else" and it refuses to connect to my phone. I'll attach the diagnostics in the morning.

That sounds weird. I would expect that Airplay "just works" as it is an Apple protocol.
It is unlikely an issue with the integration as all the commands I can send are basically the mediacontrols like Play, Pause, Next etc... I can't influence or control the audio data or connection itself.
Did AirPlay work fine without using this integration?  

Maybe try searching on the internet to see if other people ran into similar issues for your receiver?

> Also the "pause" button does not turn into a "play" button when clicked, the http page needs to be refreshed for the web page to recognize the music is paused.

The button will only update when the receiver indicates it is paused (or actually it seems to report Stop). Since you indicate that responses were slow, could it be that you refreshed around the same time the receiver reported Stop?
I can't really check as I don't have timestamps in the diagnostics so I don't see the timing, but the Stop playbackinfo does come and when I try it with my emulator and on other sources it does seem to work.

To get a better view on the timing I would need the more detailed debuglogging. If you want you can enable it with the option "Enable debug logging" which is just below the "Download diagnostics" option. Then perform the steps that should be logged and use the "Enable debug logging" option again (I think it is called "Stop logging" then) and a log will be downloaded then.

**Comment by aiden21c** [comment] 2023-02-18 02:19
Hi. Ive actually been able to rectify the above issues by doing a full power cycle on the receiver. It may have been that some airplay cache was stuck at the time and it just needed a full reset. Everything on the dev branch seems to be working as expected now so I think it was just an issue with my specific receiver at the time.

**Comment by mvdwetering** [comment] 2023-02-18 15:08
Cool, good to hear. I will make a release with the AirPlay fixes then.

**Comment by mvdwetering** [comment] 2023-03-26 13:53
I think everything discussed in this issue is done, so closing it. Feel free open a new issue when something pops up again.

**Closed by mvdwetering** 2023-03-26 13:53 UTC
