### ISSUE TITLE
Second Zone Not Detected on Yamaha RX-V583

### ISSUE THREAD

**Issue by McClutcheon** [mvdwetering/yamaha_ynca#320] opened 2024-08-17 19:36 UTC
Connected to Yamaha RX-V583 via IP LAN network. Does not recognize second zone capabilities, only entities for MAIN zone are created. Even the power on/off only works for the main zone, and not the receiver itself. If second zone is on and main zone is off, the receiver appears as powered off in HA as it is only recognizing the main zone. 

When using the Music Cast integration, it is recognized with multiple zones, and a second media player entity is created for the other zone. This works as intended, however that integration lacks customizability. I prefer this YNCA integration, and would like the same functionality . Im not sure if I am doing something incorrectly or if this is just a bug.

**Comment by mvdwetering** [comment] 2024-08-18 11:44
I have been browsing the manual a bit and it seems that the Zone A/B features on the receiver are quite different from the usual zones. The Zone A/B seems to only allow playing same audio as ZoneA in ZoneB. Is that correct? 

I got a bit confused by the "[Operating the Zone B](https://nl.yamaha.com/files/download/other_assets/9/890899/web_YJ192A0_EN1_RX-V583_om_UCRABGLFH_En_A0.pdf)" section which seems to imply you can switch input for ZoneB, but it is unclear if that is the same input as for ZoneA. For Volume the manual has a separate section on how to have volumecontrol synced between ZoneA/B or not.

Could you maybe attach some pictures of the app or webinterface of the receiver? It might make me understand better how Zone A/B would be used.

I did not see commands in the protocol to control ZoneA/B features. But we can have a look at the commands that the receiver sends. It is like in the other discussion you created. Perform the actions for interacting with ZoneB and download the diagnostics.

You can download the diagnostics from the integration entry in the menu. Sorry about the Dutch menus, I hope it is clear enough. In English is says "Download diagnostics" I believe.
![image](https://github.com/user-attachments/assets/28631924-3bb9-403a-a0f2-4dd5a1f8815b)

---
The power option offered on the mediaplayer by the integration is intended to only turn on/off the zone it belongs to, so that is working as intended. I could add a switch to power on/off the whole receiver.

**Comment by McClutcheon** [comment] 2024-08-18 16:58
You are correct in that the the zone B can only play audio from the same source as the main zone. There is an option in the settings of the receiver to sync the audio level across both zones, which works correctly. My use case is that I have the zone B of this receiver setup for my outdoor speakers, so I only require Zone On/Off and Volume Control. 

I have attached some screenshots of the Yamaha AVR iOS app as the web UI doesnt offer any controls for the receiver. You can see Basement RX (RX-V583) offers the Zone option in the bottom left. Where as the the Living Room RX (RX-V573) does not offer that option.

As for collecting the diagnostics, what method should I be using to trigger these actions? The iOS app, the remote, or my current setup thru home assistant using the MusicCast Integration?
 
![IMG_2670](https://github.com/user-attachments/assets/730e7589-ebf3-4d54-ab9a-6db15c6297bd)
![IMG_2671](https://github.com/user-attachments/assets/52304001-e796-4397-aa56-11d5e47dc1df)
![IMG_2672](https://github.com/user-attachments/assets/b4fc5a8c-5e22-49b7-bf89-b84567850bd2)
![IMG_2673](https://github.com/user-attachments/assets/c5c4ca1f-8e7e-495b-8414-8c7b3ee38974)

**Comment by mvdwetering** [comment] 2024-08-18 17:34
>As for collecting the diagnostics, what method should I be using to trigger these actions? 
>The iOS app, the remote, or my current setup thru home assistant using the MusicCast Integration?

While all probably work, it is probably best to keep it basic and just use the remote control

**Comment by McClutcheon** [comment] 2024-08-18 18:00
[config_entry-yamaha_ynca-01J5KA0CK5YCY41D8VB8Z5DTS2.json](https://github.com/user-attachments/files/16650784/config_entry-yamaha_ynca-01J5KA0CK5YCY41D8VB8Z5DTS2.json)
Attached diagnostic data after preforming zone A/B on/off actions using IR remote

**Comment by McClutcheon** [comment] 2024-08-18 18:50
> It might be nice to offer control of the volume offset (Volume Trim it is called in the manual) so could you change that a bit up and down?

Not sure what you mean by this but I will check the settings, I will grab the rest and come back. The remote offered with model has a switch at the top for independent zone control so I will do the audio commands for both zones before & after syncing volume

**Comment by McClutcheon** [comment] 2024-08-18 19:04
Found the trim setting you were looking for, I believe I got everything, may have missed a mute toggle - just let me know if you need anything else. 

Thank you very much for your wonderful integration and great support!
[config_entry-yamaha_ynca-01J5KA0CK5YCY41D8VB8Z5DTS2-2.json](https://github.com/user-attachments/files/16651209/config_entry-yamaha_ynca-01J5KA0CK5YCY41D8VB8Z5DTS2-2.json)

**Comment by mvdwetering** [comment] 2024-08-25 14:31
Ah, that trim setting seems to be for the subwoofer. That is on me I should have just pointed you to the manual to make clear which setting it was. Lets leave that for now and focus on the basic implementation first.

I have added a zone and mediaplayer for ZoneB to the integration based on the RX-V583 diagnostics which seem to work, but I would like to verify a few things before making a release.


Is it possible to change the input when in the screen for Zone B? I would expect so since the input image is there. 

Could you make a screenshot of the "Options" menu in the app when ZoneB is active? I am wondering what options are applicable to ZoneB.

--- 

And last I would like to check the behavior/support of some commands and make sure that some assumptions I made are 
correct. The attached file contains a list of commands to send, you can check the comments to see what the commands do. 

This can be done with the "Send raw YNCA command" service/action in the developertools. The complete contents of the file can be pasted into the "Raw YNCA data" box. After that perform the action, wait about 10 seconds for it to complete and get the diagnostics.

BEFORE you send the commands please turn on Zone B

[zoneb_commands.txt](https://github.com/user-attachments/files/16740617/zoneb_commands.txt)

![image](https://github.com/user-attachments/assets/58cf7867-0f29-478f-9e4a-898d515cb87d)

**Comment by mvdwetering** [comment] 2024-08-25 14:59
Note that I made a typo in the initial commands I posted. Please make sure to use "zoneb_commands_fixed.txt"

**Comment by mvdwetering** [comment] 2024-08-26 15:11
I just pushed a prerelease/beta of the integration 7.11.0b0
In HACS when you select Redownload for the integration you can select the version.

Like in the Yamaha app you should get an additional "zonedevice" with a mediaplayer for the RX-V583.

I am not sure if the RX-V573 will work. Let me know.

**Comment by McClutcheon** [comment] 2024-09-05 02:51
Sorry I was on vacation last week and was only just able to test this out. Initially I ran into issues trying to update to the beta version, I would select the proper version and redownload + restart and the version wouldn't change. I managed to get it working though, and everything shows correctly for the RX-V583 with the second media player entity being created. My only change would be that the zone b entity thats created defaults to media_player.zoneb, where I would rather it be media_player.rx_v583_zoneb to go with the main zone being media_player.rx_v583_main.

That being said, all the user functionality is there for both zones so the issue has been resolved. I noticed the Readme could also be updated to include the RX-V583. Thank you once again for the great work and support!

**Comment by mvdwetering** [comment] 2024-09-06 17:44
No worries, hope you had a good time.

Good catch on the default entity name. That should indeed include the receiver model ike the other zones. I will fix that before releasing the normal version

**Comment by mvdwetering** [comment] 2024-09-08 13:09
I fixed the default entity_id, however it won't update automatically since you installed the beta version. Home Assistant won't update entity_ids after the entity has been created. You can change it manually by clicking the entity, then click the cogwheel to get to the entity settings and change the `entity_id`

Btw, does the RX-V573 now also support the Zone A/B? 
I kind of hoped there would be Zone A/B switches in the Main zone device with this version.

**Comment by mvdwetering** [comment] 2024-10-07 18:37
Closing this as ZoneB support ofr RX-583 has been released in v7.11.0.

If additional tweaks are needed for the RX-V573 please re-open or start a new issue.

**Closed by mvdwetering** 2024-10-07 18:37 UTC
